### ISSUE TITLE
LibarchiveBackend file permission issue

### ISSUE THREAD

**Issue by rbtylee** [wfx/epack#9]
Assuming one is using the libarchive backend which should be the default, a simple illustration of this error:

```
touch test
chmod 444 test
tar -czvf archive.tar.gz test
epack -x archive.tar.gz 
```

epack then displays a Permission denied error message, in my test case:

> [Errno 13] Permission denied: u'/home/bodhi/test'

Examination of the code reveals the error occurs with line 110 in **_backend_libarchive.py_**:

```
                       with open(path, 'wb') as f:
```

My hack to fix it which may or may not be acceptable was to change this to:

```
                        os.chmod(path, 0o664)
                        with open(path, 'wb') as f:
```

Note in the same fn, latter the program resets the permission of **_path_** : 
```
                        # apply correct permission to files
                        os.chmod(path, entry.perm)
```

Hence my reasoning was this hack shouldn't effect anything else. But admittedly I have not closely examined the code or did much testing.

This is a simple illustration of the error I was trying to tell  DaveMDS  about today in IRC channel. Unfortunately at that time I hadn't tracked down the exact cause of the error.

**Comment by DaveMDS** [comment]
well... the error comes from the fact that epack is trying to overwrite your original "test" file. But the existing file is readonly (444) thus it fail to overwrite it.

Is this really a bug? do you expect epack to overwrite an existing readonly file?

**Comment by rbtylee** [comment]
OK your right here works fine if test is deleted. And no i would not expect epack to overwrite an existing readonly file. 

But the original issue I was telling you about in the IRC channel was cloning epack github repo and compressing that using file roller, I renamed the epack dir before compression as a needed step in making deb files using dh_make et al.  I usually remove .git stuff when making deb files but this time I i skipped that step. Doesn't really matter as far as the final deb file is concerned.

I was getting a permission error but now the error is different. Probably was leaving the original folder around. It seems using the shell backend does do the overwrite. But anyway, here is the error epack is giving on this:

![epack](http://i.imgur.com/nbKTvBv.png)

File-roller, xarchiver and other such apps have no issue on this file nor does the shell back end. Shouldn't matter but this is py2 version of epack on Bodhi 4.2.

**Comment by rbtylee** [comment]
This morning I cloned epack again and made an archive using the tar command. epack had no problems opening or extracting the new archive. But repeating the process using file-roller and I once again get a _[Errno 2] No such file or directory_

File-roller can of course open and extract the file. As can the shell backend of epack.

**Comment by DaveMDS** [comment]
You need to tell me how to reproduce the error, can you please attach the offending file? 
or write the steps needed to create it

**Comment by DaveMDS** [comment]
just a side note:
are you packaging for py2?
I **HIGHLY** suggest to only work with py3, I'm not testing anymore for py2, nor python-efl itself, nor any of my application. 
Python2 is way too old, long live python3 :)

**Comment by JeffHoogland** [comment]
All of Bodhi's pyefl tools are python two currently. Probably won't change them until python 3 is the default in Ubuntu.

**Comment by rbtylee** [comment]
DaveMDS, first of all your commit works here. Thanks for taking the time to look into this for an app currently not under much development :+1: 

As to python 3, Jeff builds and puts the py2 version of python-elf in Bodhis repos and all the py-efl tools he builds he does using py2-elf. Eventually [I package the py3 version of py-elf ](http://packages.bodhilinux.com/bodhi/pool/b4testing/p/python-efl/) and put that in our repos. But I am usually in no rush about that as, as far as I know, only me and Kai Huuhko use it in the Bodhi Community. Maybe a few others who aren't active on forums, IRC, et al. So I am working with both python 2 and 3. We do try to keep Bodhi apps compatible with both versions of python altho maybe I am not always diligent about that.  And we all know at some point python3 will be the default. 

If JeffHoogland doesn't mind me paraphrasing his opinions, his philosophy tends to be new is not necessarily better and if it is not broke don't fix it. Python2 and py2-elf both work. While I see advantages to using python3 and really no disadvantages, I also see no pressing need to change things in bodhi4.x (repackage a bunch of apps). Maybe we can consider this in Bodhi 5.0.
